Models/Classroom.cs
namespace Aspdotnetmcvcrud.Models
{
    public class Classroom
    {
        public int Id { get; set; }
        public int RoomNo { get; set; }

        public int TeacherId { get; set; }

        public Teacher Teacher { get; set; }

        public ICollection<Student> Students { get; set; }

    }
}

Models/Course.cs
namespace Aspdotnetmcvcrud.Models
{
    public class Course
    {
        public int Id { get; set; }
        public string course { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace Aspdotnetmcvcrud.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Student.cs
namespace Aspdotnetmcvcrud.Models
{
    public class Student
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int ClassroomId { get; set; }
        public Classroom Classroom { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
    }
}

Models/Teacher.cs
namespace Aspdotnetmcvcrud.Models
{
    public class Teacher
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Classroom Classroom { get; set; }
    }
}

Controllers/ClassroomController.cs
using Aspdotnetmcvcrud.Data;
using Aspdotnetmcvcrud.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Aspdotnetmcvcrud.Controllers
{
    public class ClassroomController : Controller
    {
        ApplicationDbContext _db;

        public ClassroomController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            var Classrooms = _db.Classrooms.Include(c => c.Teacher);
            return View(Classrooms);
        }

        [HttpGet]
        public IActionResult Students(int id)
        {
            var students = _db.Students.Where(s => s.ClassroomId == id).Include(s => s.Classroom);
            return View(students);
        }

        public IActionResult Delete(int id)
        {
            var cr = _db.Classrooms.Find(id);
            _db.Classrooms.Remove(cr);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Classroom cr)
        {
            _db.Classrooms.Add(cr);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

Controllers/CourseController.cs
using Aspdotnetmcvcrud.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Aspdotnetmcvcrud.Controllers;

public class CourseController:Controller{
    
    ApplicationDbContext _db;

    public CourseController(ApplicationDbContext db)
    {
        _db = db;
    }

    public IActionResult Index(){
        var courses = _db.Courses;
        return View(courses);
    }

    public IActionResult Students(int id){
        var Students = _db.Students.Where(s=>s.Courses.Any(c=>c.Id==id)).Include(c=>c.Classroom);
        return View(Students);
    }

    public IActionResult Delete(int id){
        var c = _db.Courses.Find(id);
        _db.Courses.Remove(c);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Aspdotnetmcvcrud.Models;

namespace Aspdotnetmcvcrud.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/StudentController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Aspdotnetmcvcrud.Models;
using Aspdotnetmcvcrud.Data;
using Microsoft.EntityFrameworkCore;

namespace Aspdotnetmcvcrud.Controllers
{
    public class StudentController : Controller
    {
        ApplicationDbContext _db;

        public StudentController(ApplicationDbContext db)
        {
            _db = db;
        }

        [HttpGet]
        public IActionResult Index()
        {
            List<Student> students = _db.Students.Include(s => s.Classroom).ToList();
            return View(students);
        }

        public IActionResult Courses(int id)
        {
            var Students = _db.Courses.Where(c=>c.Students.Any(s=>s.Id==id));
            return View(Students);
        }

        public IActionResult Delete(int id){
            var s = _db.Students.Find(id);
            _db.Students.Remove(s);
            _db.SaveChanges();
            return RedirectToAction("Index");


        }

    }
}

Controllers/TeacherController.cs
using Aspdotnetmcvcrud.Data;
using Aspdotnetmcvcrud.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Aspdotnetmcvcrud.Controllers;

public class TeacherController : Controller
{

    ApplicationDbContext _db;

    public TeacherController(ApplicationDbContext db)
    {
        _db = db;
    }

    public IActionResult Index()
    {
        var teachers = _db.Teachers.Include(t => t.Classroom);
        return View(teachers);
    }

    public IActionResult Delete(int id)
    {
        var t = _db.Teachers.Find(id);
        _db.Teachers.Remove(t);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Create(Teacher teacher)
    {
        _db.Teachers.Add(teacher);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult Edit(int id)
    {
        var t = _db.Teachers.Find(id);
        return View(t);
    }

    [HttpPost]
    public IActionResult Edit(Teacher teacher)
    {
        _db.Teachers.Update(teacher);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }



}

Views/Classroom/Create.cshtml
@model Classroom
@{
    ViewData["Title"] = "Create classroom page";
}

<div class="text-center">
    <h1>Add Classroom</h1>
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <form method="post">
                        <div class="mb-3">
                            <label asp-for="RoomNo">Enter Room Number</label>
                            <input asp-for="RoomNo" class="form-control" />
                        </div>
                        <div>
                            <label asp-for="TeacherId">Select Teacher</label>
                            @Html.DropDownListFor(model => model.TeacherId,ViewBag.Teacher as SelectList,  new { @class = "form-control"} )
                        </div>
                        <button type="submit" class="btn btn-outline-primary btn-sm">Create</button>
                </form>
            </div>
        </div>
    </div>
</div>

Views/Classroom/Index.cshtml
@model IEnumerable<Classroom>
@{
    ViewData["Classroom"] = "Classroom list";
}


<div class="d-flex justify-content-around">
<p>Classroom Page</p>
<a class="btn btn-outline-success btn-sm" asp-controller="Classroom" asp-action="Create">Add New Classroom</a>
</div>
<hr>
<table class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>RoomNo</th>
            <th>Teacher</th>
            <th>Students</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.RoomNo</td>
                <td>@item.Teacher.Name</td>
                <td><a asp-controller="Classroom" asp-action="Students" asp-route-id="@item.Id">Students</a></td>
                <td><a asp-controller="Classroom" asp-action="Edit" asp-route-id="@item.Id">Edit</a></td>
                <td><a asp-controller="Classroom" asp-action="Delete" asp-route-id="@item.Id">Delete</a></td>
            </tr>
        }
    </tbody>
</table>

Views/Classroom/Students.cshtml
@model IEnumerable<Student>
@{
    ViewData["Title"] = "Student List Page";
}

<h1>Student Page</h1>
<hr>
<table class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Classroom</th>
            <th>Courses</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Classroom.RoomNo</td>
                <td><a asp-controller="Student" asp-action="Courses" asp-route-id="@item.Id">Courses</a></td>
                <td><a asp-controller="Student" asp-action="Edit" asp-route-id="@item.Id">Edit</a></td>
                <td><a asp-controller="Student" asp-action="Delete" asp-route-id="@item.Id">Delete</a></td>
            </tr>
        }
    </tbody>
</table>

Views/Course/Index.cshtml
@model IEnumerable<Course>
@{
    ViewData["Course"] = "Course List Page";
}

<h1>Course Page</h1>
<hr>
<table class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Students</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.course</td>
                <td><a asp-controller="Course" asp-action="Students" asp-route-id="@item.Id">Students</a></td>
                <td><a asp-controller="Course" asp-action="Edit" asp-route-id="@item.Id">Edit</a></td>
                <td><a asp-controller="Course" asp-action="Delete" asp-route-id="@item.Id">Delete</a></td>
            </tr>
        }
    </tbody>
</table>

Views/Course/Students.cshtml
@model IEnumerable<Student>
@{
    ViewData["Course"] = "Course List Page";
}

<h1>Students Page</h1>
<hr>
<table class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>RoomNo</th>
            <th>Courses</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td><a asp-controller="Classroom" asp-action="Students" asp-route-id="@item.ClassroomId">@item.Classroom.RoomNo</a></td>
                <td><a asp-controller="Student" asp-action="Courses" asp-route-id="@item.Id">Courses</a></td>
                <td><a asp-controller="Course" asp-action="Edit" asp-route-id="@item.Id">Edit</a></td>
                <td><a asp-controller="Course" asp-action="Delete" asp-route-id="@item.Id">Delete</a></td>
            </tr>
        }
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">cccccccccccccc</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <h1>hellp</h1>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Aspdotnetmcvcrud</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Aspdotnetmcvcrud.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Aspdotnetmcvcrud</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Student" asp-action="Index">Student</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Teacher" asp-action="Index">Teacher</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Classroom" asp-action="Index">Classroom</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Course" asp-action="Index">Course</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Aspdotnetmcvcrud - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Views/Shared/_Notification.cshtml
@if(TempData["success"]!=null){
    <h2>@TempData["success"]</h2>
}

@if(TempData["error"]!=null){
    <h2>@TempData["error"]</h2>
}

Views/Student/Courses.cshtml
@model IEnumerable<Course>
@{
    ViewData["Title"] = "Student Course List Page";
}

<h1>Courses for Student </h1>
<hr>
<table class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Course</th>
            <th>Students</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.course</td>
                <td><a asp-controller="Course" asp-action="Students" asp-route-id="@item.Id">Students</a></td>
                <td><a asp-controller="Student" asp-action="Edit" asp-route-id="@item.Id">Edit</a></td>
                <td><a asp-controller="Student" asp-action="Delete" asp-route-id="@item.Id">Delete</a></td>
            </tr>
        }
    </tbody>
</table>

Views/Student/Index.cshtml
@model IEnumerable<Student>
@{
    ViewData["Title"] = "Student List Page";
}

<h1>Student Page</h1>
<hr>
<table class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Classroom</th>
            <th>Courses</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td><a asp-controller="Classroom" asp-action="Students" asp-route-id="@item.ClassroomId">@item.Classroom.RoomNo</a></td>
                <td><a asp-controller="Student" asp-action="Courses" asp-route-id="@item.Id">Courses</a></td>
                <td><a asp-controller="Student" asp-action="Edit" asp-route-id="@item.Id">Edit</a></td>
                <td><a asp-controller="Student" asp-action="Delete" asp-route-id="@item.Id">Delete</a></td>
            </tr>
        }
    </tbody>
</table>

Views/Teacher/Create.cshtml
@model Teacher
@{
    ViewData["Title"] = "Create Teacher Page";
}

<div class="text-center">
    <h1>Add Teacher</h1>
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <form method="post">
                        <div class="mb-3">
                            <label asp-for="Name">Teacher Name</label>
                            <input asp-for="Name" class="form-control" />
                        </div>
                        <button type="submit" class="btn btn-outline-primary btn-sm">Create</button>
                </form>
            </div>
        </div>
    </div>
</div>

Views/Teacher/Edit.cshtml
@model Teacher
@{
    ViewData["Title"] = "Edit Teacher Page";
}

<div class="text-center">
    <h1>Edit Teacher</h1>
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <form method="post">
                        <div class="mb-3">
                            <label asp-for="Name">Teacher Name</label>
                            <input asp-for="Name" class="form-control" />
                        </div>
                        <button type="submit" class="btn btn-outline-primary btn-sm">Update</button>
                </form>
            </div>
        </div>
    </div>
</div>

Views/Teacher/Index.cshtml
@model IEnumerable<Teacher>
@{
    ViewData["Teacher"] = "Teacher List page";
}

<div class="d-flex justify-content-around">
<p>Teacher Page</p>
<a class="btn btn-outline-success btn-sm" asp-controller="Teacher" asp-action="Create">Add New Teacher</a>
</div>
<hr>
<table class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Classroom</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@(item.Classroom==null?"":item.Classroom.RoomNo)</td>
                <td><a asp-controller="Teacher" asp-action="Edit" asp-route-id="@item.Id">Edit</a></td>
                <td><a asp-controller="Teacher" asp-action="Delete" asp-route-id="@item.Id">Delete</a></td>
            </tr>
        }
    </tbody>
</table>